plugins:
   - jekyll/tagging
   - jekyll/paginate
tag_page_layout: tag_page
tag_page_dir: tag
tag_page_data:
  sitemap: false
paginate: 5
paginate_path: "/blog/page-:num/"

# Build settings
encoding: utf-8


markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
